@serverID = 630aee8c97cba3d40fea6044
@token =  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMGFhNzdkZGQ0NDY3ZWM1Mjc3OWI2NSIsImlhdCI6MTY2MTY5OTA2NiwiZXhwIjoxNjYxNzAyNjY2fQ.V_e0U0mzPQm-6FVAGacApdzDAJE_z2SmywJkns5jcac
### DELETE REQUEST
DELETE http://localhost:3003/api/blogs/{{serverID}}
# Content-Type: application/json
Authorization: {{token}}

### GET SPECIFIC ITEM FROM SERVER
GET http://localhost:3003/api/blogs/{{serverID}}
# Content-Type: application/json
Authorization: {{token}}

### GET ALL FROM SERVER REQUEST
GET http://localhost:3003/api/blogs
Authorization: {{token}}

### POST REQUEST
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: {{token}}

{ 
  "title": "Root blog to TWO",
  "author": "Root",
  "url": "http://www.GiuseppeNeedsAJob.com",
  "userId": "630aa5eae14aeff17cabea8a"
}

### PUT REQUEST 
PUT   http://localhost:3003/api/blogs/{{serverID}}
Content-Type: application/json
Authorization: {{token}}

{ 
  "title": "Giuseppe's UPDATED",
  "author": "Giuseppe Fazzolari",
  "url": "http://www.GiuseppeFazzolariHasGotAJob.com",
  "likes": 100000
}
