@serverID = 631cd4c9cdd428c48cce5f58
@token =  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZhenpvbGFyaTE3IiwiaWQiOiI2MzFjY2NlZWJhMDA5ZmY4YzM0NmRjNTIiLCJpYXQiOjE2NjI4MzM2NTcsImV4cCI6MTY2MjgzNzI1N30.ouf9qjPvOvpQgvdGYzZ24fhPFSPwYGGcTODowb7JNEM

@userId = 631ccceeba009ff8c346dc52
### DELETE REQUEST
DELETE http://localhost:3003/api/blogs/{{serverID}}
# Content-Type: application/json
Authorization: {{token}}

### GET SPECIFIC ITEM FROM SERVER
GET http://localhost:3003/api/blogs/{{serverID}}
# Content-Type: application/json
Authorization: {{token}}

### GET ALL FROM SERVER REQUEST
GET http://localhost:3003/api/blogs
Authorization: {{token}}

### POST REQUEST
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: {{token}}

{ 
  "title": "Blog With Comments...THREE?",
  "author": "Fazzolari17",
  "url": "http://www.GiuseppeNeedsAJob.com",
  "userId": "{{userId}}"
}

### PUT REQUEST 
PUT   http://localhost:3003/api/blogs/{{serverID}}
Content-Type: application/json
Authorization: {{token}}

{ 
  "title": "FAzzolari17 ONE ",
  "author": "Fazzolari17",
  "url": "http://www.GiuseppeFazzolariHasGotAJob.com",
  "likes": 100000
}
