@userID = 631ccceeba009ff8c346dc52

@token = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZhenpvbGFyaTE3IiwiaWQiOiI2MzFjY2NlZWJhMDA5ZmY4YzM0NmRjNTIiLCJpYXQiOjE2NjI4MzU0MDIsImV4cCI6MTY2MjgzOTAwMn0.3D4r4RUss28IJE50E2JPk3VLg4pTsx6bZAl3YZsSl2k
### DELETE REQUEST
DELETE http://localhost:3003/api/users/{{userID}}

### GET SPECIFIC ITEM FROM SERVER
GET http://localhost:3003/api/users/{{userID}}


### GET ALL FROM SERVER REQUEST
GET http://localhost:3003/api/users
Authorization: {{token}}

### POST REQUEST
POST http://localhost:3003/api/users
Content-Type: application/json

{ 
  "username": "Root",
  "name": "Giuseppe Fazzolari",
  "password": "password"
}


###
GET http://localhost:3003/api/users


